[features]
seeds = false
[programs.localnet]
token_delegate = "TKDLLzzmBD7Rwbz6PS4XDFDr5w4ApSBRNC4wninsX7M"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "/tmp/ramdisk/export/key-deploy-1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
